-- AlterTable
ALTER TABLE `WritingLesson` ADD COLUMN `level` ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED') NOT NULL DEFAULT 'BEGINNER',
    ADD COLUMN `type` ENUM('EMAILS', 'DIARIES', 'ESSAYS', 'ARTICLES', 'STORIES', 'REPORTS') NOT NULL DEFAULT 'EMAILS';
